name: flutter_clock_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_easylogger: ^2.3.3
  flutter_local_notifications: ^14.1.1
  flutter_timezone: ^1.0.6
  intl: ^0.18.1
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
        - asset: assets/fonts/Avenir-Heavy.ttf
          weight: 700
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir-Light.ttf
          weight: 300
